openapi: 3.0.1
info:
  title: Blogs API
  description: |-
    Nesta documenta√ß√£o feita com Swagger (OpenAPI), voc√™ tem amplo acesso a todas as rotas j√° dispon√≠veis, assim como o resultado de um requisi√ß√£o, tanto positivo quanto negativo.
    
    Al√©m do mais, voc√™ pode tamb√©m testar a API diretamente por aqui, sem precisar de outro Client API. Para testar basta clicar na rota deseja e ent√£o clicar em `Try it out`.

    Lembre-se que √© IMPRESCIND√çVEL o uso do **token** nas rotas com o √≠cone de cadeado (üîí), gerado pela rota **/login** e **/user (POST)**.
    
    Para utilizar o token, voc√™ dever√° clicando no bot√£o verde `Authorize üîì`, inseri-lo na caixa de texto e ent√£o clicar em **Authorize**. Pronto! Desta forma, poder√° usufruir de todas as rotas.

    
  version: 1.0.0
  contact:
    name: Adelson
    url: https://www.linkedin.com/in/adelson-lima/
servers:
  - url: http://127.0.0.1:3000/v1
paths:
  /login:
    post:
      tags:
        - Login
      summary: Ir√° autenticar o usu√°rio.
      description: Atrav√©s desta requisi√ß√£o, √© enviado o **email** e **password** para o back-end, que ir√° validar a exist√™ncia destes dados no banco de dados e caso existam, ir√° retornar um Bearer Token gerado pelo JWT.
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
            examples:
              1:
                value:
                  email: lewishamilton@gmail.com
                  password: "123456"
              2:
                value:
                  email: michaelschumacher@gmail.com
                  password: "123456"
      responses:
        200:
          description: Ir√° retornar um token para futuras valida√ß√µes, o que te garante acesso a todas as outras rotas da API.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token: 
                    type: string
              example:
                token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        400:
          description: Ir√° retornar uma mensagem de erro sempre que uma requisi√ß√£o n√£o tiver os campos necess√°rios.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                "Sem email":
                  value:
                    message: "\"password\" is required"
                "Sem a senha":
                  value:
                    message: "\"email\" is required"
                "Campo extra":
                  value:
                    message: "\"name\" is not allowed"
        404:
          description: Ir√° retornar uma mensagem informando que n√£o h√° um registro com os dados enviados na requisi√ß√£o.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
              example:
                message: "User not found"
  /user:
    post:
      tags:
        - User
      summary: Ir√° registra os dados referente a um novo usu√°rio.
      description: Quando receber os dados atrav√©s de uma requisi√ß√£o, ir√° valida-los e caso o **email** j√° n√£o esteja registrado, todos os dados ser√£o registrado no banco de dados. Por fim, retornar√° um token criado para o novo usu√°rio.
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - displayName
                - email
                - password
              properties:
                displayName: 
                  type: string
                email:
                  type: string
                password:
                  type: string 
                image:
                  type: string
            examples:
              1:
                value:
                  displayName: Lewis Hamilton
                  email: lewishamilton@gmail.com
                  password: "123456"
                  image: https://upload.wikimedia.org/wikipedia/commons/1/18/Lewis_Hamilton_2016_Malaysia_2.jpg
              2:
                value:
                  displayName: Michael Schumacher
                  email: michaelcchumacher@gmail.com
                  password: "123456"
                  image: https://sportbuzz.uol.com.br/media/_versions/gettyimages-52491565_widelg.jpg
      responses:
        201:
          description: Ir√° retornar um token exclusivo para o novo usu√°rio registrado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                example:
                  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        400:
          description: Uma mensagem de erro √© retornada ao n√£o informar um dos campos necess√°rio, algum campo extra ou valore incorreto para determinado tipo.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                "Campo extra":
                  value:
                    message: "\"easy\" is not allowed"
                "Sem o campo email":
                  value:
                    message: "\"email\" is required"
                "Sem o campo displayName":
                  value:
                    message: "\"displayName\" is required"
        409:
          description: Ir√° retornar uma mensagem de erro ao tentar cadastrar um usu√°rio com o mesmo **email**.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: "User already registered"
    get:
      tags:
        - User
      summary: Ir√° retornar todos os registros de todos os usu√°rios cadastrados.
      description: Todos os dados de todos os usu√°rios registrados no banco de dados ser√° retornado dentro de uma vetor.
      responses:
        200:
          description: Ir√° retornar todos os registros de todos os usu√°rios cadastrados.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    displayName: 
                      type: string
                    email:
                      type: string
                    password:
                      type: string 
                    image:
                      type: string
              examples:
                "Quando h√° registros":
                  value:
                  - id: 1
                    displayName: Lewis Hamilton
                    email: lewishamilton@gmail.com
                    image: https://upload.wikimedia.org/wikipedia/commons/1/18/Lewis_Hamilton_2016_Malaysia_2.jpg
                  - id: 2
                    displayName: Michael Schumacher
                    email: michaelcchumacher@gmail.com
                    image: https://sportbuzz.uol.com.br/media/_versions/gettyimages-52491565_widelg.jpg
                "N√£o h√° registros":
                  value:
                    []
  /user/{id}:
    get:
      tags:
        - User
      summary: Ir√° retornar todos os dados do usu√°rio baseado na pesquisa do seu ID.
      description: Ao receber o ID referente a um registro, a aplica√ß√£o vai verificar se existe um usu√°rio. Em caso positivo, ir√° retorna todos os dados. Caso n√£o exista nenhum registro referente ao ID da busca, uma mensagem de erro ser√° retornada.
      parameters:
          - name: id
            in: path
            required: true
            schema:
              type: number
            example:
              1
      responses:
        200:
          description: Ir√° retornar todos os dados do registro referente ao ID pesquisado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  displayName:
                    type: string
                  email:
                    type: string
                  password:
                    type: string 
                  image:
                    type: string
              examples:
                1:
                  value:
                    id: 1
                    displayName: Lewis Hamilton
                    email: lewishamilton@gmail.com
                    image: https://upload.wikimedia.org/wikipedia/commons/1/18/Lewis_Hamilton_2016_Malaysia_2.jpg
                2:
                  value:
                    id: 2
                    displayName: Michael Schumacher
                    email: michaelcchumacher@gmail.com
                    image: https://sportbuzz.uol.com.br/media/_versions/gettyimages-52491565_widelg.jpg
        404:
          description: Ir√° retornar uma mensagem de erro pois n√£o foi encontrado um registro referente ao ID da requisi√ß√£o.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: "User not found"
  /categories:
    post:
      tags:
        - Category
      summary: Ir√° registrar os dados referente a uma nova categoria.
      description: Ao receber uma requisi√ß√£o, ir√° verificar se h√° campos extras ou a aus√™ncia do campo **name**. Caso n√£o haja problema com os dados recebidos, ir√° verificar ent√£o se o nome da categoria j√° existe. Caso j√° exista a categoria, retornar√° um erro, do contr√°rio, ir√° registrar a nova categoria.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
            examples:
              1:
                value:
                  name: Inova√ß√£o
              2:
                value:
                  name: Escola
              3:
                value:
                  name: Trabalho
      responses:
        201:
          description: Ir√° criar o registro referente a categoria, com o nome recebido na requisi√ß√£o.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  name:
                    type: string
              example:
                id: 1
                name: Inova√ß√£o
        400:
          description: Ir√° retornar uma mensagem de erro dizendo que h√° problemas com os campos recebidos na requisi√ß√£o.
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensagem:
                    type: string
              examples:
                "Sem enviar o 'name'":
                  value:
                    message: "\"name\" is required"
                "Enviando campo extra":
                  value:
                    message: "\"campo_desnecess√°rio\" is not allowed"
        409:
          description: Ir√° retornar uma mensagem de erro informando que j√° existe esta categoria registrada no banco de dados.
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensagem:
                    type: string
              example:
                message: Category already exists

    get:
      tags:
        - Category
      summary: Ir√° retornar todas as categorias.
      description: Ir√° retornar todas as categorias j√° registradas no banco de dados.
      responses:
        200:
          description: Todos os dados de todas as categorias ser√£o retornados.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name: 
                      type: string
              examples:
                "Quando h√° registros":
                  value:
                  - id: 1
                    name: Inova√ß√£o
                  - id: 2
                    name: Escola
                "N√£o h√° registros":
                  value:
                    []
  /post:
    get:
      tags:
        - Post
      summary: Ir√° retornar todos os dados registrados, referentes as postagens.
      description: Todos os dados de todas as postagens ser√£o retornados, assim como a associa√ß√£o que descreve o usu√°rio que fez a determinada postagem.
      responses:
        200:
          description: Todos os dados ser√£o retornados.
          content:
            application/json:
              schema:
                type: object
                properties:
                    id:
                      type: number
                    title:
                      type: string 
                    content:
                      type: string 
                    userId:
                      type: number
                    published:
                      type: string 
                    updated:
                      type: string
                    user:
                      type: object
                      properties:
                        id:
                          type: number
                        displayName:
                          type: string
                        email:
                          type: string
                        password:
                          type: string 
                        image:
                          type: string
                    categories:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: number
                          name:
                            type: string
              examples:
                "Quando h√° registros":
                  value:
                    - id: 1
                      title: Post do Ano
                      content: Melhor post do ano
                      userId: 1
                      published: 2011-08-01T19:58:00.000Z
                      updated: 2011-08-01T19:58:51.000Z
                      user: 
                          id: 1
                          displayName: Lewis Hamilton
                          email: lewishamilton@gmail.com
                          image: https://upload.wikimedia.org/wikipedia/commons/1/18/Lewis_Hamilton_2016_Malaysia_2.jpg
                      categories: 
                          - id: 1
                            name: Inova√ß√£o
                    - id: 2
                      title: Vamos que vamos
                      content: Foguete n√£o tem r√©
                      userId: 1
                      published: 2011-08-01T19:58:00.000Z
                      updated: 2011-08-01T19:58:51.000Z
                      user: 
                          id: 1
                          displayName: Lewis Hamilton
                          email: lewishamilton@gmail.com
                          image: https://upload.wikimedia.org/wikipedia/commons/1/18/Lewis_Hamilton_2016_Malaysia_2.jpg
                      
                      categories: 
                          - id: 2
                            name: Escola
                "Quando n√£o nenhum registros":
                  value: []
  /post/search?q=:
    get:
      tags:
        - Post
      summary: Ir√° retornar todos os dados referente a pesquisa.
      description: Ao receber uma requisi√ß√£o com a query `q`, ser√° feita uma verifica√ß√£o no campo **title** e **content** de todos os dados referentes as postagens criadas.
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
          examples:
            "Buscando pelo termo 'Ano'":
              value: Ano
            "Buscando pelo termo 'r√©'":
              value: r√©
      responses:
        200:
          description: Vai retornar todos os dados.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                      id:
                        type: number
                      title:
                        type: string 
                      content:
                        type: string 
                      userId:
                        type: number
                      published:
                        type: string 
                      updated:
                        type: string
                      user:
                        type: object
                        properties:
                          id:
                            type: number
                          displayName:
                            type: string
                          email:
                            type: string
                          password:
                            type: string 
                          image:
                            type: string
                      categories:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: number
                            name:
                              type: string
              examples:
                "Pesquisando por 'Ano'":
                  value:
                  - id: 1
                    title: Post do Ano
                    content: Melhor post do ano
                    userId: 1
                    published: 2011-08-01T19:58:00.000Z
                    updated: 2011-08-01T19:58:51.000Z
                    user: 
                        id: 1
                        displayName: Lewis Hamilton
                        email: lewishamilton@gmail.com
                        image: https://upload.wikimedia.org/wikipedia/commons/1/18/Lewis_Hamilton_2016_Malaysia_2.jpg
                    categories: 
                        - id: 1
                          name: Inova√ß√£o
                "Pesquisando por 'r√©'":
                  value:
                    - id: 2
                      title: Vamos que vamos
                      content: Foguete n√£o tem r√©
                      userId: 1
                      published: 2011-08-01T19:58:00.000Z
                      updated: 2011-08-01T19:58:51.000Z
                      user: 
                          id: 1
                          displayName: Lewis Hamilton
                          email: lewishamilton@gmail.com
                          image: https://upload.wikimedia.org/wikipedia/commons/1/18/Lewis_Hamilton_2016_Malaysia_2.jpg
                      
                      categories: 
                          - id: 2
                            name: Escola
                "Pesquisando por 'Adelson'":
                  value: []

components:
  securitySchemes:
    toke_jwt_bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - toke_jwt_bearer:
    - read
  
                